version: "3.9" 
services:
   web:
       build: .
       ports:
           - "9090:9090"
       environment:
           MONGODB_URI: mongodb+srv://IAESTE:123234@cluster0.ouanz.mongodb.net/?retryWrites=true&w=majority